/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.co.kleindelao.demo.airportdisplay;

public class App {
    public static void main(String[] args) {
        System.out.println("Nothing here yet");
    }
}
